namespace AnonKey_Backend.Authentication;

/// <summary>
/// Represents a token generated by the JWT algorithm.
/// </summary>
public class Token
{
    /// <summary>
    /// Create a new token object.
    /// </summary>
    public Token(string tokenString, int expiresIn)
    {
        TokenString = tokenString;
        ExpiresIn = expiresIn;
    }

    /// <summary>
    /// The token string itself.
    /// </summary>
    public string TokenString { get; set; }
    /// <summary>
    /// The time in seconds the token expires in.
    /// </summary>
    public int ExpiresIn { get; set; }
}
